name: Json Validator

on:
  pull_request:
    paths:
      - '**.json'
  push:
    branches:
      - main
    paths:
      - '**.json'

jobs:
  json-validator:
    name: Json Validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate Json
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y --no-install-recommends
          sudo pip3 install json-spec
          json validate --schema-file=php/containers-schema.json --document-file=php/containers.json
